"""Add cv_url and cover_letter_url to candidate_profiles

Revision ID: fca8bd3669d2
Revises: d6fcda97e884
Create Date: 2025-09-15 11:11:28.289081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca8bd3669d2'
down_revision: Union[str, Sequence[str], None] = 'd6fcda97e884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('cv_url', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('cover_letter_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'cover_letter_url')
    op.drop_column('candidate_profiles', 'cv_url')
    # ### end Alembic commands ###
